---
title: "Report for the results"
output: html_document
params:
  alpha_draw: NA
  graph_data: NA
header-includes:
  \usepackage{booktabs}
---

```{r}
library(knitr)
library(xtable)
alpha <- params$alpha_draw
edges <- params$graph_data$edges
nodes <- params$graph_data$nodes
edges
nodes
```

```{r, echo=FALSE, results='asis'}
library(knitr)
library(xtable)
t1 <- kable(nodes,
  # cbind('Items'=c(#"Number of patients",
  #             "Number of predictors",
  #             "Number of events "),
  #           'Values'=c(#params$n,
  #              params$p,
  #              params$Ef)), 
  format = "latex", booktabs = TRUE)
           
t2 <- kable(edges,
  # cbind('Items'=c("Shrinkage factor",
  #             "Adjusted Cox-Snell R-squared",
  #             "Absolute difference",
  #             "Margin of error"),
  #           'Values'=c(params$S_VH,
  #              params$csR2_adj,
  #              params$d,
  #              params$error_mar)), 
  format = "latex", booktabs = TRUE)
cat(c("\\begin{table}[!htb]
    \\begin{minipage}{.5\\linewidth}
      \\caption{Data characteristics}
      \\centering",
        t1,
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{Input desired values}",
        t2,
    "\\end{minipage} 
\\end{table}"
))  
```


