
tabHome <- tabPanel("Home", icon=icon("home", lib = "glyphicon"),
                      fluidRow(
                        column(12,includeHTML("www/home_title.html")),
                        br(),br(),
                        column(8,includeHTML("www/home.html")),
                        br(),br(),
                        br(),br(),
                        br(),br(),
                        br(),br(),
                        br(),br(),
                        br(),br(),
                        column(4,style = "background-color: skyblue;",
                               h3("User guidance"),
                               HTML("To work out your own result, you can download the R markdown file, or use the <em>Draw</em>/<em>Example</em> tab depending on the senario."),
                               # h5("Learning Materials"),
                               # p("The slides for the course."),
                               # downloadButton("downloadSlide", label = "Slides"),
                               # br(),br(),
                               h5("R markdown File"),
                               HTML("You can run the core function <code>gMCP_app</code> directly. The rejection result and adjusted <i>p</i>-values are avaliable."),
                               downloadButton("downloadRMD", label = "Document"),
                               br(),br(),
                               h5("Key operation video (Draw)"),
                               HTML("You can directly add nodes and edges in the Draw tab to obtaion the result"),
                               tags$video(id="video1", type = "video/mp4",width="350", height="240",
                                          src = "Draw_video.mp4", controls = "controls"),
                               br(),br(),
                               h5("Key operation video (Example)"),
                               HTML("You can simply choose the specific procedure (e.g. <em>Bonferroni-Holm Test</em>) in the <em>Example</em> tab"),
                               tags$video(id="video2", type = "video/mp4",width="350", height="240",
                                          src = "Example_video.mp4", controls = "controls"),
                               br(),br(),
                               br(),br()),
                        column(12,includeHTML("www/reference.html")),
                        br(),br()
                      ))
                    
                    
                    