
tabHome <- tabPanel("Home", icon=icon("home", lib = "glyphicon"),
                    fluidRow(
                      column(12,includeHTML("www/home_title.html")),
                      br(),br(),
                      column(8,includeHTML("www/home.html")),
                      br(),br(),
                      br(),br(),
                      br(),br(),
                      br(),
                      br(),br(),
                      column(4,style = "background-color: skyblue;",
                             h3("User guidance"),
                             HTML("To implement the graphical approach, you can use the <em>Draw </em>/<em> Example</em> tab, or download the R markdown file to use in the command line in R."),
                             # h5("Learning Materials"),
                             # p("The slides for the course."),
                             # downloadButton("downloadSlide", label = "Slides"),
                             # br(),br(),
                             h5("R markdown File"),
                             HTML("You can run the core function <code>graph_app</code> directly. The rejection results and adjusted <i>p</i>-values are avaliable, 
                                   but there is no graph visualization."),
                             br(),
                             downloadButton("downloadRMD", label = "Document"),
                             br(),br(),
                             h5("Key operation video (Draw)"),
                             HTML("You can directly add nodes and edges in the Draw tab."),
                             tags$video(id="video1", type = "video/mp4",width="350", height="240",
                                        src = "Draw.mp4", controls = "controls"),
                             br(),br(),
                             h5("Key operation video (Examples)"),
                             HTML("You can choose commonly used procedures (e.g. <em>Bonferroni-Holm Test</em>) in the <em>Example</em> tab."),
                             tags$video(id="video2", type = "video/mp4",width="350", height="240",
                                        src = "Example.mp4", controls = "controls"),
                             br(),br(),
                             br(),br()),
                      column(12,includeHTML("www/reference.html")),
                      br(),br()))
                    
                    
                    
