# the most recent version of visNetwork
# devtools::install_github("datastorm-open/visNetwork")
library(visNetwork)
library(shiny)
library(shinyMatrix) # interactive matrix input
library(network)
library(shinythemes)
library(DT)
library(ggnetwork)
library(ggplot2)
library(gridExtra)
library(data.table)
library(shinyWidgets)
library(shinycssloaders)
library(ggpubr)
library(shinyAce)
library(shinyBS)
library(reshape2)
library(shinyThings)
library(dplyr)
library(shinydashboard)
library(shinyjs)
library(rintrojs) # introBox
library(DiagrammeR)
library(shinyalert)
library(cowplot)
library(jsonlite)  # guideline shinyjs
library(markdown)
library(rmarkdown)